spring.application.name=minebuddy

server.port=${SERVER_PORT:8083}

spring.datasource.url=jdbc:${MARIADB_PRIVATE_URL:mariadb://localhost:3312/minebuddy_db}
spring.datasource.username=${MARIADB_USER:minebuddy}
spring.datasource.password=${MARIADB_PASSWORD:minebuddy}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}

logging.level.root=${LOG_LEVEL:INFO}

app.jwt.secret=${JWT_SECRET:563fd5f533521686e1718682a7d15421e7c1b23d3f05f474b6be2e6ae189a422}
app.jwt.expiry-hours=${JWT_EXPIRY_HOURS:8}

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200}